import type { Metadata } from 'next';
import { Geist, Geist_Mono, DotGothic16 } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const dotGothic16 = DotGothic16({
  variable: '--font-dot-gothic-16',
  subsets: ['latin'],
  weight: '400',
  display: "swap",
  style: ["normal"],
  fallback: ["sans-serif"],
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${dotGothic16.variable} antialiased`}>{children}</body>
    </html>
  );
}
