import type { Metadata } from 'next';
import { Silkscreen, Source_Code_Pro } from 'next/font/google';
import './globals.css';

const silkscreen = Silkscreen({
  variable: '--font-silkscreen',
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  style: ['normal'],
  fallback: ['sans-serif'],
  preload: true,
});

const geo = Source_Code_Pro({
  variable: '--font-scp',
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  style: ['normal'],
  fallback: ['sans-serif'],
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${silkscreen?.variable} ${geo?.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
